version: '3.3'

services:
  apache:
    build: ./apache
    #restart: always
    ports:
      - 80:80 # physical port : container port
      - 443:443  # physical port : container port
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./apache/data:/var/www:rw
    networks:
      - lampnet
  
  db:
    image: mariadb:10.4.6
    #restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=pi_parking_monitor
      - TZ=Asia/Taipei
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - lampnet

  adminer:
    build: ./adminer
    #restart: always
    ports:
      - 8080:8080
    #environment:
    #  DB_SSL_KEY: '/ssl/private.key'
    #  DB_SSL_CERT: '/ssl/certificate.crt'
    #  DB_SSL_CA: '/ssl/ca_bundle.crt'
    depends_on:
      - db
    networks:
      - lampnet

volumes:
  homepage:

networks:
  lampnet:
    driver: bridge
